### ISSUE TITLE
wx package giving error

### ISSUE THREAD

**Issue by anupamkarn** [Buraksk/python-ftp-server#1]
when running "pip install -r requirements.txt" wx package is giving error "Could not find a version that satisfies the requirement wx==3.0.2.0", tried to upgrade pip but then this error "ImportError: cannot import name main" was thrown anybody has any idea about it?

**Comment by burakisk** [comment]
It may be related your python version. You can check my another repository which is to be similar this via the link https://github.com/ManInTheBit/FTP-Client-Server-Application
